// <auto-generated />
using System;
using GBastos.Desafio_Meta.InfraEstructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GBastos.Desafio_Meta.InfraEstructure.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210516162515_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GBastos.Desafio_Meta.ApplicationCore.Audiencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DtHrAudiencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmissoraId")
                        .HasColumnType("int");

                    b.Property<long>("PtsAudiencia")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EmissoraId");

                    b.ToTable("Audiencia");
                });

            modelBuilder.Entity("GBastos.Desafio_Meta.ApplicationCore.Emissora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Emissora");
                });

            modelBuilder.Entity("GBastos.Desafio_Meta.ApplicationCore.Audiencia", b =>
                {
                    b.HasOne("GBastos.Desafio_Meta.ApplicationCore.Emissora", "Emissora")
                        .WithMany("Audiencias")
                        .HasForeignKey("EmissoraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emissora");
                });

            modelBuilder.Entity("GBastos.Desafio_Meta.ApplicationCore.Emissora", b =>
                {
                    b.Navigation("Audiencias");
                });
#pragma warning restore 612, 618
        }
    }
}
